import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/event/event_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/fund/fund_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/group_report/group_report_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/utils/app_types.dart';

import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/user/user_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/group/group_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/api/work_area/work_area_model.dart';

class DummyHelper {
  //WORK AREAS
  static final List<WorkAreaModel> workAreas = [
    WorkAreaModel(id: 1, name: "Kantor Pusat", createdAt: DateTime(2023, 1, 1)),
    WorkAreaModel(id: 2, name: "Cabang Jakarta Selatan"),
    WorkAreaModel(id: 3, name: "Cabang Jakarta Barat"),
    WorkAreaModel(id: 4, name: "Cabang Tangerang"),
    WorkAreaModel(id: 5, name: "Cabang Bekasi"),
    WorkAreaModel(id: 6, name: "Cabang Bogor"),
    WorkAreaModel(id: 7, name: "Cabang Depok"),
    WorkAreaModel(id: 8, name: "Cabang Bandung"),
    WorkAreaModel(id: 9, name: "Cabang Surabaya"),
    WorkAreaModel(id: 10, name: "Cabang Malang"),
    WorkAreaModel(id: 11, name: "Cabang Medan"),
    WorkAreaModel(id: 12, name: "Cabang Makassar"),
    WorkAreaModel(id: 13, name: "Cabang Semarang"),
    WorkAreaModel(id: 14, name: "Cabang Yogyakarta"),
    WorkAreaModel(id: 15, name: "Cabang Denpasar"),
  ];
  static WorkAreaModel wa(int id) => workAreas.firstWhere((w) => w.id == id);

  // USERS
  static final List<UserModel> users = [
    UserModel(
      id: 1,
      name: "Rizky Pratama",
      memberNumber: "MBR-1023",
      identityNumber: "3275012301980001",
      birthDate: DateTime(1998, 1, 23),
      phoneNumber: "081298112233",
      address: "Jakarta Selatan",
      occupation: "Staff Administrasi",
      identityCardPhoto: "",
      selfPhoto: "",
      emailVerifiedAt: DateTime(2023, 3, 10),
      role: "member",
      isActive: true,
      workArea: wa(2),
      group: null,
      createdAt: DateTime(2023, 3, 1),
      updatedAt: DateTime(2023, 3, 1),
    ),
    UserModel(
      id: 2,
      name: "Dewi Anggraini",
      memberNumber: "MBR-1044",
      identityNumber: "3674031506950004",
      birthDate: DateTime(1995, 6, 15),
      phoneNumber: "082144556677",
      address: "Tangerang",
      occupation: "Guru SD",
      identityCardPhoto: "",
      selfPhoto: "",
      emailVerifiedAt: DateTime(2023, 5, 20),
      role: "member",
      isActive: true,
      workArea: wa(4),
      group: null,
      createdAt: DateTime(2023, 5, 10),
      updatedAt: DateTime(2023, 5, 10),
    ),
    UserModel(
      id: 3,
      name: "Arif Setiawan",
      memberNumber: "MBR-1087",
      identityNumber: "3517011111910008",
      birthDate: DateTime(1991, 11, 11),
      phoneNumber: "085799112200",
      address: "Surabaya",
      occupation: "Teknisi IT",
      identityCardPhoto: "",
      selfPhoto: "",
      emailVerifiedAt: null,
      role: "member",
      isActive: true,
      workArea: wa(9),
      group: null,
      createdAt: DateTime(2023, 6, 14),
      updatedAt: DateTime(2023, 6, 14),
    ),
    UserModel(
      id: 4,
      name: "Siti Marlina",
      memberNumber: "MBR-1102",
      identityNumber: "3276012404990007",
      birthDate: DateTime(1999, 4, 24),
      phoneNumber: "081312778899",
      address: "Bekasi",
      occupation: "Perawat",
      identityCardPhoto: "",
      selfPhoto: "",
      emailVerifiedAt: DateTime(2024, 1, 8),
      role: "member",
      isActive: false,
      workArea: wa(5),
      group: null,
      createdAt: DateTime(2024, 1, 5),
      updatedAt: DateTime(2024, 1, 5),
    ),
    UserModel(
      id: 5,
      name: "Hendra Wijaya",
      memberNumber: "MBR-1120",
      identityNumber: "3174022907870003",
      birthDate: DateTime(1987, 7, 29),
      phoneNumber: "081290334455",
      address: "Bandung",
      occupation: "Wiraswasta",
      identityCardPhoto: "",
      selfPhoto: "",
      emailVerifiedAt: null,
      role: "admin",
      isActive: true,
      workArea: wa(8),
      group: null,
      createdAt: DateTime(2024, 3, 2),
      updatedAt: DateTime(2024, 3, 2),
    ),
  ];
  static UserModel user(int id) => users.firstWhere((u) => u.id == id);

  // GROUPS
  static final List<GroupModel> groups = [
    GroupModel(
      id: 1,
      number: 1,
      description: "Kelompok simpan pinjam A",
      sharedLiabilityFundAmount: 1500000,
      groupFundAmount: 2000000,
      socialFundAmount: 500000,
      isActive: true,
      workArea: wa(2),
      chairman: user(1),
      facilitator: user(5),
      createdAt: DateTime(2023, 3, 1),
      updatedAt: DateTime(2023, 3, 1),
    ),
    GroupModel(
      id: 2,
      number: 2,
      description: "Kelompok usaha mikro B",
      sharedLiabilityFundAmount: 1200000,
      groupFundAmount: 1800000,
      socialFundAmount: 400000,
      isActive: true,
      workArea: wa(4),
      chairman: user(2),
      facilitator: user(1),
      createdAt: DateTime(2023, 4, 10),
      updatedAt: DateTime(2023, 4, 10),
    ),
    GroupModel(
      id: 3,
      number: 3,
      description: "Kelompok simpanan Yogyakarta",
      sharedLiabilityFundAmount: 2000000,
      groupFundAmount: 2600000,
      socialFundAmount: 600000,
      isActive: true,
      workArea: wa(14),
      chairman: user(3),
      facilitator: user(4),
      createdAt: DateTime(2023, 6, 2),
      updatedAt: DateTime(2023, 6, 2),
    ),
    GroupModel(
      id: 4,
      number: 4,
      description: "Kelompok ekonomi Bandung",
      sharedLiabilityFundAmount: 1750000,
      groupFundAmount: 2100000,
      socialFundAmount: 475000,
      isActive: false,
      workArea: wa(8),
      chairman: user(5),
      facilitator: user(3),
      createdAt: DateTime(2023, 8, 12),
      updatedAt: DateTime(2023, 8, 12),
    ),
    GroupModel(
      id: 5,
      number: 5,
      description: "Kelompok wanita mandiri Makassar",
      sharedLiabilityFundAmount: 1600000,
      groupFundAmount: 2200000,
      socialFundAmount: 550000,
      isActive: true,
      workArea: wa(12),
      chairman: user(4),
      facilitator: user(2),
      createdAt: DateTime(2023, 9, 1),
      updatedAt: DateTime(2023, 9, 1),
    ),
  ];

  static final List<GroupReportModel> groupReports = [
    GroupReportModel(
      id: '1',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 12,
      incomingMembersPercentage: 15,
      outgoingMembers: 3,
      outgoingMembersPercentage: 5,
      totalMembers: 45,
      totalMembersPercentage: 10,
      administrationOrderPercentage: 90,
      depositOrderPercentage: 85,
      attendancePercentage: 88,
      finalOrganizationScorePercentage: 86,
      loanParticipationPb: 12,
      loanParticipationBbm: 8,
      loanParticipationStore: 15,
      cashParticipation: 2000000,
      cashParticipationPercentage: 75,
      savingParticipation: 1500000,
      savingParticipationPercentage: 60,
      meetingDepositPercentage: 80,
      loanBalancePb: 3000000,
      loanBalanceBbm: 1500000,
      loanBalanceStore: 2500000,
      receivableScorePercentage: 20,
      finalFinanceScorePercentage: 89,
      combinedScorePercentage: 87,
      criteria: 1,
      group: groups[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '2',
      quarter: DateTime(2025, 4, 1),
      incomingMembers: 8,
      incomingMembersPercentage: 10,
      outgoingMembers: 2,
      outgoingMembersPercentage: 3,
      totalMembers: 38,
      totalMembersPercentage: 7,
      administrationOrderPercentage: 88,
      depositOrderPercentage: 80,
      attendancePercentage: 83,
      finalOrganizationScorePercentage: 82,
      loanParticipationPb: 10,
      loanParticipationBbm: 5,
      loanParticipationStore: 12,
      cashParticipation: 1800000,
      cashParticipationPercentage: 70,
      savingParticipation: 1300000,
      savingParticipationPercentage: 55,
      meetingDepositPercentage: 78,
      loanBalancePb: 2800000,
      loanBalanceBbm: 1100000,
      loanBalanceStore: 2000000,
      finalFinanceScorePercentage: 85,
      combinedScorePercentage: 84,
      receivableScorePercentage: 20,
      criteria: 2,
      group: groups[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '3',
      quarter: DateTime(2025, 9, 1),
      incomingMembers: 15,
      incomingMembersPercentage: 18,
      outgoingMembers: 4,
      outgoingMembersPercentage: 6,
      totalMembers: 50,
      totalMembersPercentage: 12,
      administrationOrderPercentage: 92,
      depositOrderPercentage: 87,
      attendancePercentage: 90,
      finalOrganizationScorePercentage: 89,
      loanParticipationPb: 14,
      loanParticipationBbm: 9,
      loanParticipationStore: 17,
      cashParticipation: 2500000,
      cashParticipationPercentage: 78,
      savingParticipation: 1700000,
      savingParticipationPercentage: 68,
      meetingDepositPercentage: 84,
      loanBalancePb: 3500000,
      loanBalanceBbm: 1900000,
      loanBalanceStore: 3000000,
      finalFinanceScorePercentage: 91,
      combinedScorePercentage: 90,
      receivableScorePercentage: 20,
      criteria: 1,
      group: groups[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '4',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 9,
      incomingMembersPercentage: 11,
      outgoingMembers: 1,
      outgoingMembersPercentage: 2,
      totalMembers: 40,
      totalMembersPercentage: 8,
      administrationOrderPercentage: 83,
      depositOrderPercentage: 79,
      attendancePercentage: 81,
      finalOrganizationScorePercentage: 80,
      loanParticipationPb: 11,
      loanParticipationBbm: 4,
      loanParticipationStore: 10,
      cashParticipation: 1600000,
      cashParticipationPercentage: 65,
      savingParticipation: 1200000,
      savingParticipationPercentage: 50,
      meetingDepositPercentage: 76,
      loanBalancePb: 2400000,
      loanBalanceBbm: 900000,
      loanBalanceStore: 1800000,
      finalFinanceScorePercentage: 82,
      receivableScorePercentage: 20,
      combinedScorePercentage: 81,
      criteria: 3,
      group: groups[3],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '5',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 11,
      incomingMembersPercentage: 14,
      outgoingMembers: 3,
      outgoingMembersPercentage: 4,
      totalMembers: 42,
      totalMembersPercentage: 9,
      administrationOrderPercentage: 87,
      depositOrderPercentage: 82,
      attendancePercentage: 85,
      finalOrganizationScorePercentage: 84,
      loanParticipationPb: 13,
      loanParticipationBbm: 7,
      loanParticipationStore: 14,
      cashParticipation: 2100000,
      cashParticipationPercentage: 72,
      savingParticipation: 1400000,
      savingParticipationPercentage: 58,
      meetingDepositPercentage: 79,
      loanBalancePb: 2700000,
      loanBalanceBbm: 1300000,
      loanBalanceStore: 2200000,
      finalFinanceScorePercentage: 88,
      combinedScorePercentage: 86,
      receivableScorePercentage: 20,
      criteria: 2,
      group: groups[4],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '6',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 6,
      incomingMembersPercentage: 7,
      outgoingMembers: 2,
      outgoingMembersPercentage: 3,
      totalMembers: 30,
      totalMembersPercentage: 5,
      administrationOrderPercentage: 78,
      depositOrderPercentage: 70,
      attendancePercentage: 75,
      finalOrganizationScorePercentage: 74,
      loanParticipationPb: 6,
      loanParticipationBbm: 3,
      loanParticipationStore: 8,
      cashParticipation: 1200000,
      cashParticipationPercentage: 50,
      savingParticipation: 800000,
      savingParticipationPercentage: 40,
      meetingDepositPercentage: 65,
      loanBalancePb: 1500000,
      loanBalanceBbm: 700000,
      loanBalanceStore: 1000000,
      finalFinanceScorePercentage: 76,
      receivableScorePercentage: 20,
      combinedScorePercentage: 75,
      criteria: 4,
      group: groups[5],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<FundModel> Funds = [
    FundModel(
      month: 1,
      year: 2024,
      amount: 1500000,
      fundType: FundType.groupFund,
      group: groups[0],
    ),
    FundModel(
      month: 2,
      year: 2024,
      amount: 1700000,
      fundType: FundType.groupFund,
      group: groups[1],
    ),
    FundModel(
      month: 3,
      year: 2024,
      amount: 1300000,
      fundType: FundType.sharedLiabilityFund,
      group: groups[1],
    ),
    FundModel(
      month: 4,
      year: 2024,
      amount: 2100000,
      fundType: FundType.socialFund,
      group: groups[1],
    ),
    FundModel(
      month: 5,
      year: 2024,
      amount: 1600000,
      fundType: FundType.sharedLiabilityFund,
      group: groups[1],
    ),
    FundModel(
      month: 6,
      year: 2024,
      amount: 2200000,
      fundType: FundType.groupFund,
      group: groups[1],
    ),
  ];
}
