import 'package:koperasi_sekar_kartini_mobile_app/app/models/event_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/fund_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/group_member_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/group_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/group_report_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/user_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/work_area_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/types/enum/role_enum.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/utils/app_types.dart';

class DummyHelper {
  static final List<WorkAreaModel> dummyWorkAreas = [
    WorkAreaModel(
      id: 1,
      districtName: 'Sukaraja',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 2,
      districtName: 'Cibadak',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 3,
      districtName: 'Warudoyong',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 4,
      districtName: 'Lembursitu',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 5,
      districtName: 'Cikole',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 6,
      districtName: 'Citamiang',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 7,
      districtName: 'Gunungpuyuh',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 8,
      districtName: 'Baros',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 9,
      districtName: 'Purbaratu',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 10,
      districtName: 'Indihiang',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<UserModel> dummyUsers = [
    UserModel(
      id: 1,
      name: 'Raka Febrian',
      role: RoleEnum.groupLeader,
      nationalId: '1234567890123456',
      phone: '081234567890',
      birthDate: DateTime(1998, 5, 12),
      address: 'Jl. Melati No. 10, Jakarta',
      job: 'Software Engineer',
      email: 'raka@example.com',
      idCard: 'idcard_user_001.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 2,
      name: 'Siti Rahma',
      role: RoleEnum.admin,
      nationalId: '1234567890123456',
      phone: '082345678901',
      birthDate: DateTime(1995, 7, 20),
      address: 'Jl. Mawar No. 5, Bandung',
      job: 'Pengurus',
      email: 'siti@example.com',
      idCard: 'idcard_user_002.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 3,
      name: 'Taufik Hidayat',
      role: RoleEnum.employee,
      nationalId: '1234567890123456',
      phone: '083456789012',
      birthDate: DateTime(1990, 3, 28),
      address: 'Jl. Kenanga No. 12, Surabaya',
      job: 'Manager',
      email: 'taufik@example.com',
      idCard: 'idcard_user_003.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 4,
      name: 'Dewi Kartika',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '084567890123',
      birthDate: DateTime(1997, 11, 15),
      address: 'Jl. Anggrek No. 3, Yogyakarta',
      job: 'Guru',
      email: 'dewi@example.com',
      idCard: 'idcard_user_004.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 5,
      name: 'Bagas Saputra',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '085678901234',
      birthDate: DateTime(1992, 2, 8),
      address: 'Jl. Dahlia No. 22, Semarang',
      job: 'Akuntan',
      email: 'bagas@example.com',
      idCard: 'idcard_user_005.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 6,
      name: 'Siti Aminah',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '086789012345',
      birthDate: DateTime(1996, 9, 2),
      address: 'Jl. Flamboyan No. 18, Medan',
      job: 'Ibu Rumah Tangga',
      email: 'aminah@example.com',
      idCard: 'idcard_user_006.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 7,
      name: 'Norman Reedus',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '08138294898',
      birthDate: DateTime(1996, 9, 2),
      address: 'Jl. Arteri No. 22, Lampung',
      job: 'Penjahit',
      email: 'aminah@example.com',
      idCard: 'idcard_user_006.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<EventModel> dummyEvents = [
    EventModel(
      id: 1,
      title: 'Rapat Anggota Tahunan',
      type: EventType.groupEvent,
      description: '''
    [
      {"insert": "Agenda Rapat:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pembukaan\\n2. Laporan Keuangan 2025\\n3. Pembahasan Program 2026\\n4. Pemilihan Pengurus Baru\\n5. Penutupan\\n\\n"},
      {"insert": "Tempat:", "attributes": {"italic": true}},
      {"insert": " Aula Koperasi Sekar Kartini\\n"},
      {"insert": "Waktu:", "attributes": {"italic": true}},
      {"insert": " 09.00 WIB - Selesai\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 12, 5, 9, 0),
      location: 'Aula Koperasi Sekar Kartini',
      image: 'https://example.com/images/event_rapat_tahunan.jpg',
      user: dummyUsers[0],
      group: dummyGroups[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 2,
      title: 'Pelatihan Keuangan Pribadi',
      type: EventType.coopEvent,
      description: '''
    [
      {"insert": "Materi Pelatihan:\\n", "attributes": {"bold": true}},
      {"insert": "1. Dasar-dasar Manajemen Keuangan\\n2. Mengatur Anggaran Rumah Tangga\\n3. Tips Menabung Efektif\\n4. Studi Kasus dan Diskusi\\n\\n"},
      {"insert": "Narasumber:", "attributes": {"italic": true}},
      {"insert": " Ibu Ratna Sari, S.E. (Konsultan Keuangan)\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 11, 20, 13, 30),
      location: 'Ruang Serbaguna Lt. 2',
      image: 'https://example.com/images/event_pelatihan_keuangan.jpg',
      user: dummyUsers[1],
      group: dummyGroups[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 3,
      title: 'Bakti Sosial Akhir Tahun',
      type: EventType.coopEvent,
      description: '''
    [
      {"insert": "Kegiatan Bakti Sosial:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pembagian Sembako\\n2. Pemeriksaan Kesehatan Gratis\\n3. Donor Darah\\n\\n"},
      {"insert": "Lokasi:", "attributes": {"italic": true}},
      {"insert": " Kantor Desa Karanganyar\\n"},
      {"insert": "Jam:", "attributes": {"italic": true}},
      {"insert": " 08.00 WIB\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 12, 28, 8, 0),
      location: 'Kantor Desa Karanganyar',
      image: 'https://example.com/images/event_baksos.jpg',
      user: dummyUsers[2],
      group: dummyGroups[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 4,
      title: 'Workshop Digital Marketing',
      type: EventType.coopEvent,
      description: '''
    [
      {"insert": "Rundown Workshop:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pengenalan Digital Marketing\\n2. Strategi Media Sosial\\n3. Praktik Optimasi Konten\\n4. Tanya Jawab\\n\\n"},
      {"insert": "Pemateri:", "attributes": {"italic": true}},
      {"insert": " Bapak Agus Santoso, M.M. (Digital Strategist)\\n"}
    ]
    ''',
      dateTime: DateTime(2026, 1, 10, 10, 0),
      location: 'Balai Pertemuan Kota',
      image: 'https://example.com/images/event_workshop_digital.jpg',
      user: dummyUsers[3],
      group: dummyGroups[3],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 5,
      title: 'Family Gathering Koperasi',
      type: EventType.coopEvent,
      description: '''
    [
      {"insert": "Susunan Acara:\\n", "attributes": {"bold": true}},
      {"insert": "1. Registrasi Peserta\\n2. Games dan Outbound\\n3. Makan Siang Bersama\\n4. Doorprize dan Hiburan\\n5. Penutupan\\n\\n"},
      {"insert": "Lokasi:", "attributes": {"italic": true}},
      {"insert": " Taman Wisata Alam Sumber Ria\\n"},
      {"insert": "Dresscode:", "attributes": {"italic": true}},
      {"insert": " Kaos Putih & Celana Jeans\\n"}
    ]
    ''',
      dateTime: DateTime(2026, 2, 14, 7, 30),
      location: 'Taman Wisata Alam Sumber Ria',
      image: 'https://example.com/images/event_family_gathering.jpg',
      user: dummyUsers[4],
      group: dummyGroups[4],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 6,
      title: 'Syukuran Rumah Baru Bu Nurul',
      type: EventType.groupEvent,
      description: '''
      [
        { "insert": "Rundown:\\n", "attributes": { "bold": true } },
        { "insert": "1. Pembukaan\\n2. Pembacaan Yasin\\n3. Ramah Tamah\\n4. Foto Bersama\\n5. Penutup\\n" },
        { "insert": "\\n" },
        { "insert": "Tempat:", "attributes": { "italic": true } },
        { "insert": " Rumah Bu Nurul\\n" }
      ]
    ''',
      dateTime: DateTime(2025, 11, 8, 20, 0, 0),
      location: 'Jl. Melati no.05, Kec. Patrang, Kab. Jember',
      user: dummyUsers[5],
      group: dummyGroups[5],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<GroupModel> dummyGroups = [
    GroupModel(
      id: 1,
      number: "01",
      regulation: "Peraturan Kelompok No. 01/2025",
      jointLiabilityFundAmount: 50000,
      groupFundAmount: 30000,
      socialFundAmount: 20000,
      totalJointLiabilityFund: 1500000,
      totalGroupFund: 900000,
      totalSocialFund: 600000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: 2,
      number: "02",
      regulation: "Peraturan Kelompok No. 02/2025",
      jointLiabilityFundAmount: 52000,
      groupFundAmount: 31000,
      socialFundAmount: 21000,
      totalJointLiabilityFund: 1520000,
      totalGroupFund: 910000,
      totalSocialFund: 610000,
      isActive: false,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[2],
      facilitator: dummyUsers[1],
    ),
    GroupModel(
      id: 3,
      number: "03",
      regulation: "Peraturan Kelompok No. 03/2025",
      jointLiabilityFundAmount: 54000,
      groupFundAmount: 32000,
      socialFundAmount: 22000,
      totalJointLiabilityFund: 1540000,
      totalGroupFund: 920000,
      totalSocialFund: 620000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: 4,
      number: "04",
      regulation: "Peraturan Kelompok No. 04/2025",
      jointLiabilityFundAmount: 56000,
      groupFundAmount: 33000,
      socialFundAmount: 23000,
      totalJointLiabilityFund: 1560000,
      totalGroupFund: 930000,
      totalSocialFund: 630000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: 5,
      number: "05",
      regulation: "Peraturan Kelompok No. 05/2025",
      jointLiabilityFundAmount: 58000,
      groupFundAmount: 34000,
      socialFundAmount: 24000,
      totalJointLiabilityFund: 1580000,
      totalGroupFund: 940000,
      totalSocialFund: 640000,
      isActive: false,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: 6,
      number: "06",
      regulation: "Peraturan Kelompok No. 06/2025",
      jointLiabilityFundAmount: 60000,
      groupFundAmount: 35000,
      socialFundAmount: 25000,
      totalJointLiabilityFund: 1600000,
      totalGroupFund: 950000,
      totalSocialFund: 650000,
      isActive: true,
      workArea: dummyWorkAreas[1],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: 7,
      number: "07",
      regulation: "Peraturan Kelompok No. 07/2025",
      jointLiabilityFundAmount: 62000,
      groupFundAmount: 36000,
      socialFundAmount: 26000,
      totalJointLiabilityFund: 1620000,
      totalGroupFund: 960000,
      totalSocialFund: 660000,
      isActive: false,
      workArea: dummyWorkAreas[1],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: 8,
      number: "08",
      regulation: "Peraturan Kelompok No. 08/2025",
      jointLiabilityFundAmount: 64000,
      groupFundAmount: 37000,
      socialFundAmount: 27000,
      totalJointLiabilityFund: 1640000,
      totalGroupFund: 970000,
      totalSocialFund: 670000,
      isActive: true,
      workArea: dummyWorkAreas[2],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: 9,
      number: "09",
      regulation: "Peraturan Kelompok No. 09/2025",
      jointLiabilityFundAmount: 66000,
      groupFundAmount: 38000,
      socialFundAmount: 28000,
      totalJointLiabilityFund: 1660000,
      totalGroupFund: 980000,
      totalSocialFund: 680000,
      isActive: true,
      workArea: dummyWorkAreas[3],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: 10,
      number: "10",
      regulation: "Peraturan Kelompok No. 10/2025",
      jointLiabilityFundAmount: 68000,
      groupFundAmount: 39000,
      socialFundAmount: 29000,
      totalJointLiabilityFund: 1680000,
      totalGroupFund: 990000,
      totalSocialFund: 690000,
      isActive: false,
      workArea: dummyWorkAreas[3],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<GroupMemberModel> dummyGroupMembers = [
    GroupMemberModel(
      id: 1,
      isActive: true,
      note: 'Anggota aktif dengan kontribusi rutin.',
      user: dummyUsers[4],
      group: dummyGroups[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupMemberModel(
      id: 2,
      isActive: false,
      note: 'Status nonaktif karena tidak hadir 3 bulan.',
      user: dummyUsers[5],
      group: dummyGroups[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupMemberModel(
      id: 3,
      isActive: true,
      note: 'Ketua kelompok.',
      user: dummyUsers[6],
      group: dummyGroups[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<GroupReportModel> dummyGroupReports = [
    GroupReportModel(
      id: '1',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 12,
      incomingMembersPercentage: 15,
      outgoingMembers: 3,
      outgoingMembersPercentage: 5,
      totalMembers: 45,
      totalMembersPercentage: 10,
      administrationOrderPercentage: 90,
      depositOrderPercentage: 85,
      attendancePercentage: 88,
      finalOrganizationScorePercentage: 86,
      loanParticipationPb: 12,
      loanParticipationBbm: 8,
      loanParticipationStore: 15,
      cashParticipation: 2000000,
      cashParticipationPercentage: 75,
      savingParticipation: 1500000,
      savingParticipationPercentage: 60,
      meetingDepositPercentage: 80,
      loanBalancePb: 3000000,
      loanBalanceBbm: 1500000,
      loanBalanceStore: 2500000,
      finalFinanceScorePercentage: 89,
      combinedScorePercentage: 87,
      criteria: 1,
      group: dummyGroups[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '2',
      quarter: DateTime(2025, 4, 1),
      incomingMembers: 8,
      incomingMembersPercentage: 10,
      outgoingMembers: 2,
      outgoingMembersPercentage: 3,
      totalMembers: 38,
      totalMembersPercentage: 7,
      administrationOrderPercentage: 88,
      depositOrderPercentage: 80,
      attendancePercentage: 83,
      finalOrganizationScorePercentage: 82,
      loanParticipationPb: 10,
      loanParticipationBbm: 5,
      loanParticipationStore: 12,
      cashParticipation: 1800000,
      cashParticipationPercentage: 70,
      savingParticipation: 1300000,
      savingParticipationPercentage: 55,
      meetingDepositPercentage: 78,
      loanBalancePb: 2800000,
      loanBalanceBbm: 1100000,
      loanBalanceStore: 2000000,
      finalFinanceScorePercentage: 85,
      combinedScorePercentage: 84,
      criteria: 2,
      group: dummyGroups[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '3',
      quarter: DateTime(2025, 9, 1),
      incomingMembers: 15,
      incomingMembersPercentage: 18,
      outgoingMembers: 4,
      outgoingMembersPercentage: 6,
      totalMembers: 50,
      totalMembersPercentage: 12,
      administrationOrderPercentage: 92,
      depositOrderPercentage: 87,
      attendancePercentage: 90,
      finalOrganizationScorePercentage: 89,
      loanParticipationPb: 14,
      loanParticipationBbm: 9,
      loanParticipationStore: 17,
      cashParticipation: 2500000,
      cashParticipationPercentage: 78,
      savingParticipation: 1700000,
      savingParticipationPercentage: 68,
      meetingDepositPercentage: 84,
      loanBalancePb: 3500000,
      loanBalanceBbm: 1900000,
      loanBalanceStore: 3000000,
      finalFinanceScorePercentage: 91,
      combinedScorePercentage: 90,
      criteria: 1,
      group: dummyGroups[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '4',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 9,
      incomingMembersPercentage: 11,
      outgoingMembers: 1,
      outgoingMembersPercentage: 2,
      totalMembers: 40,
      totalMembersPercentage: 8,
      administrationOrderPercentage: 83,
      depositOrderPercentage: 79,
      attendancePercentage: 81,
      finalOrganizationScorePercentage: 80,
      loanParticipationPb: 11,
      loanParticipationBbm: 4,
      loanParticipationStore: 10,
      cashParticipation: 1600000,
      cashParticipationPercentage: 65,
      savingParticipation: 1200000,
      savingParticipationPercentage: 50,
      meetingDepositPercentage: 76,
      loanBalancePb: 2400000,
      loanBalanceBbm: 900000,
      loanBalanceStore: 1800000,
      finalFinanceScorePercentage: 82,
      combinedScorePercentage: 81,
      criteria: 3,
      group: dummyGroups[3],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '5',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 11,
      incomingMembersPercentage: 14,
      outgoingMembers: 3,
      outgoingMembersPercentage: 4,
      totalMembers: 42,
      totalMembersPercentage: 9,
      administrationOrderPercentage: 87,
      depositOrderPercentage: 82,
      attendancePercentage: 85,
      finalOrganizationScorePercentage: 84,
      loanParticipationPb: 13,
      loanParticipationBbm: 7,
      loanParticipationStore: 14,
      cashParticipation: 2100000,
      cashParticipationPercentage: 72,
      savingParticipation: 1400000,
      savingParticipationPercentage: 58,
      meetingDepositPercentage: 79,
      loanBalancePb: 2700000,
      loanBalanceBbm: 1300000,
      loanBalanceStore: 2200000,
      finalFinanceScorePercentage: 88,
      combinedScorePercentage: 86,
      criteria: 2,
      group: dummyGroups[4],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupReportModel(
      id: '6',
      quarter: DateTime(2025, 1, 1),
      incomingMembers: 6,
      incomingMembersPercentage: 7,
      outgoingMembers: 2,
      outgoingMembersPercentage: 3,
      totalMembers: 30,
      totalMembersPercentage: 5,
      administrationOrderPercentage: 78,
      depositOrderPercentage: 70,
      attendancePercentage: 75,
      finalOrganizationScorePercentage: 74,
      loanParticipationPb: 6,
      loanParticipationBbm: 3,
      loanParticipationStore: 8,
      cashParticipation: 1200000,
      cashParticipationPercentage: 50,
      savingParticipation: 800000,
      savingParticipationPercentage: 40,
      meetingDepositPercentage: 65,
      loanBalancePb: 1500000,
      loanBalanceBbm: 700000,
      loanBalanceStore: 1000000,
      finalFinanceScorePercentage: 76,
      combinedScorePercentage: 75,
      criteria: 4,
      group: dummyGroups[5],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<FundModel> dummyFunds = [
    FundModel(
      month: 1,
      year: 2024,
      amount: 1500000,
      fundType: FundType.groupFund,
      group: dummyGroups[0],
    ),
    FundModel(
      month: 2,
      year: 2024,
      amount: 1700000,
      fundType: FundType.groupFund,
      group: dummyGroups[1],
    ),
    FundModel(
      month: 3,
      year: 2024,
      amount: 1300000,
      fundType: FundType.jointLiabilityFund,
      group: dummyGroups[1],
    ),
    FundModel(
      month: 4,
      year: 2024,
      amount: 2100000,
      fundType: FundType.socialFund,
      group: dummyGroups[1],
    ),
    FundModel(
      month: 5,
      year: 2024,
      amount: 1600000,
      fundType: FundType.jointLiabilityFund,
      group: dummyGroups[1],
    ),
    FundModel(
      month: 6,
      year: 2024,
      amount: 2200000,
      fundType: FundType.groupFund,
      group: dummyGroups[1],
    ),
  ];
}
