import 'package:koperasi_sekar_kartini_mobile_app/app/models/event_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/group_member_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/group_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/user_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/models/work_area_model.dart';
import 'package:koperasi_sekar_kartini_mobile_app/app/types/enum/role_enum.dart';

class DummyHelper {
  static final List<WorkAreaModel> dummyWorkAreas = [
    WorkAreaModel(
      id: 'WORK-AREA-001',
      districtName: 'Sukaraja',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-002',
      districtName: 'Cibadak',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-003',
      districtName: 'Warudoyong',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-004',
      districtName: 'Lembursitu',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-005',
      districtName: 'Cikole',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-006',
      districtName: 'Citamiang',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-007',
      districtName: 'Gunungpuyuh',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-008',
      districtName: 'Baros',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-009',
      districtName: 'Purbaratu',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    WorkAreaModel(
      id: 'WORK-AREA-010',
      districtName: 'Indihiang',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<UserModel> dummyUsers = [
    UserModel(
      id: 'USER-001',
      name: 'Raka Febrian',
      role: RoleEnum.groupLeader,
      nationalId: '1234567890123456',
      phone: '081234567890',
      birthDate: DateTime(1998, 5, 12),
      address: 'Jl. Melati No. 10, Jakarta',
      job: 'Software Engineer',
      email: 'raka@example.com',
      idCard: 'idcard_user_001.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-002',
      name: 'Siti Rahma',
      role: RoleEnum.admin,
      nationalId: '1234567890123456',
      phone: '082345678901',
      birthDate: DateTime(1995, 7, 20),
      address: 'Jl. Mawar No. 5, Bandung',
      job: 'Pengurus',
      email: 'siti@example.com',
      idCard: 'idcard_user_002.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-003',
      name: 'Taufik Hidayat',
      role: RoleEnum.employee,
      nationalId: '1234567890123456',
      phone: '083456789012',
      birthDate: DateTime(1990, 3, 28),
      address: 'Jl. Kenanga No. 12, Surabaya',
      job: 'Manager',
      email: 'taufik@example.com',
      idCard: 'idcard_user_003.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-004',
      name: 'Dewi Kartika',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '084567890123',
      birthDate: DateTime(1997, 11, 15),
      address: 'Jl. Anggrek No. 3, Yogyakarta',
      job: 'Guru',
      email: 'dewi@example.com',
      idCard: 'idcard_user_004.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-005',
      name: 'Bagas Saputra',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '085678901234',
      birthDate: DateTime(1992, 2, 8),
      address: 'Jl. Dahlia No. 22, Semarang',
      job: 'Akuntan',
      email: 'bagas@example.com',
      idCard: 'idcard_user_005.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-006',
      name: 'Siti Aminah',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '086789012345',
      birthDate: DateTime(1996, 9, 2),
      address: 'Jl. Flamboyan No. 18, Medan',
      job: 'Ibu Rumah Tangga',
      email: 'aminah@example.com',
      idCard: 'idcard_user_006.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    UserModel(
      id: 'USER-007',
      name: 'Norman Reedus',
      role: RoleEnum.groupMember,
      nationalId: '1234567890123456',
      phone: '08138294898',
      birthDate: DateTime(1996, 9, 2),
      address: 'Jl. Arteri No. 22, Lampung',
      job: 'Penjahit',
      email: 'aminah@example.com',
      idCard: 'idcard_user_006.jpg',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<EventModel> dummyEvents = [
    EventModel(
      id: 'EVENT-001',
      title: 'Rapat Anggota Tahunan',
      description: '''
    [
      {"insert": "Agenda Rapat:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pembukaan\\n2. Laporan Keuangan 2025\\n3. Pembahasan Program 2026\\n4. Pemilihan Pengurus Baru\\n5. Penutupan\\n\\n"},
      {"insert": "Tempat:", "attributes": {"italic": true}},
      {"insert": " Aula Koperasi Sekar Kartini\\n"},
      {"insert": "Waktu:", "attributes": {"italic": true}},
      {"insert": " 09.00 WIB - Selesai\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 12, 5, 9, 0),
      location: 'Aula Koperasi Sekar Kartini',
      image: 'https://example.com/images/event_rapat_tahunan.jpg',
      user: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 'EVENT-002',
      title: 'Pelatihan Keuangan Pribadi',
      description: '''
    [
      {"insert": "Materi Pelatihan:\\n", "attributes": {"bold": true}},
      {"insert": "1. Dasar-dasar Manajemen Keuangan\\n2. Mengatur Anggaran Rumah Tangga\\n3. Tips Menabung Efektif\\n4. Studi Kasus dan Diskusi\\n\\n"},
      {"insert": "Narasumber:", "attributes": {"italic": true}},
      {"insert": " Ibu Ratna Sari, S.E. (Konsultan Keuangan)\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 11, 20, 13, 30),
      location: 'Ruang Serbaguna Lt. 2',
      image: 'https://example.com/images/event_pelatihan_keuangan.jpg',
      user: dummyUsers[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 'EVENT-003',
      title: 'Bakti Sosial Akhir Tahun',
      description: '''
    [
      {"insert": "Kegiatan Bakti Sosial:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pembagian Sembako\\n2. Pemeriksaan Kesehatan Gratis\\n3. Donor Darah\\n\\n"},
      {"insert": "Lokasi:", "attributes": {"italic": true}},
      {"insert": " Kantor Desa Karanganyar\\n"},
      {"insert": "Jam:", "attributes": {"italic": true}},
      {"insert": " 08.00 WIB\\n"}
    ]
    ''',
      dateTime: DateTime(2025, 12, 28, 8, 0),
      location: 'Kantor Desa Karanganyar',
      image: 'https://example.com/images/event_baksos.jpg',
      user: dummyUsers[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 'EVENT-004',
      title: 'Workshop Digital Marketing',
      description: '''
    [
      {"insert": "Rundown Workshop:\\n", "attributes": {"bold": true}},
      {"insert": "1. Pengenalan Digital Marketing\\n2. Strategi Media Sosial\\n3. Praktik Optimasi Konten\\n4. Tanya Jawab\\n\\n"},
      {"insert": "Pemateri:", "attributes": {"italic": true}},
      {"insert": " Bapak Agus Santoso, M.M. (Digital Strategist)\\n"}
    ]
    ''',
      dateTime: DateTime(2026, 1, 10, 10, 0),
      location: 'Balai Pertemuan Kota',
      image: 'https://example.com/images/event_workshop_digital.jpg',
      user: dummyUsers[3],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 'EVENT-005',
      title: 'Family Gathering Koperasi',
      description: '''
    [
      {"insert": "Susunan Acara:\\n", "attributes": {"bold": true}},
      {"insert": "1. Registrasi Peserta\\n2. Games dan Outbound\\n3. Makan Siang Bersama\\n4. Doorprize dan Hiburan\\n5. Penutupan\\n\\n"},
      {"insert": "Lokasi:", "attributes": {"italic": true}},
      {"insert": " Taman Wisata Alam Sumber Ria\\n"},
      {"insert": "Dresscode:", "attributes": {"italic": true}},
      {"insert": " Kaos Putih & Celana Jeans\\n"}
    ]
    ''',
      dateTime: DateTime(2026, 2, 14, 7, 30),
      location: 'Taman Wisata Alam Sumber Ria',
      image: 'https://example.com/images/event_family_gathering.jpg',
      user: dummyUsers[4],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    EventModel(
      id: 'EVENT-006',
      title: 'Syukuran Rumah Baru Bu Nurul',
      description: '''
      [
        { "insert": "Rundown:\\n", "attributes": { "bold": true } },
        { "insert": "1. Pembukaan\\n2. Pembacaan Yasin\\n3. Ramah Tamah\\n4. Foto Bersama\\n5. Penutup\\n" },
        { "insert": "\\n" },
        { "insert": "Tempat:", "attributes": { "italic": true } },
        { "insert": " Rumah Bu Nurul\\n" }
      ]
    ''',
      dateTime: DateTime(2025, 11, 8, 20, 0, 0),
      location: 'Jl. Melati no.05, Kec. Patrang, Kab. Jember',
      user: dummyUsers[5],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final dummyGroups = [
    GroupModel(
      id: "GROUP-001",
      number: "01",
      regulation: "Peraturan Kelompok No. 01/2025",
      jointLiabilityFundAmount: 50000,
      groupFundAmount: 30000,
      socialFundAmount: 20000,
      totalJointLiabilityFund: 1500000,
      totalGroupFund: 900000,
      totalSocialFund: 600000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: "GROUP-002",
      number: "02",
      regulation: "Peraturan Kelompok No. 02/2025",
      jointLiabilityFundAmount: 52000,
      groupFundAmount: 31000,
      socialFundAmount: 21000,
      totalJointLiabilityFund: 1520000,
      totalGroupFund: 910000,
      totalSocialFund: 610000,
      isActive: false,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[2],
      facilitator: dummyUsers[1],
    ),
    GroupModel(
      id: "GROUP-003",
      number: "03",
      regulation: "Peraturan Kelompok No. 03/2025",
      jointLiabilityFundAmount: 54000,
      groupFundAmount: 32000,
      socialFundAmount: 22000,
      totalJointLiabilityFund: 1540000,
      totalGroupFund: 920000,
      totalSocialFund: 620000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: "GROUP-004",
      number: "04",
      regulation: "Peraturan Kelompok No. 04/2025",
      jointLiabilityFundAmount: 56000,
      groupFundAmount: 33000,
      socialFundAmount: 23000,
      totalJointLiabilityFund: 1560000,
      totalGroupFund: 930000,
      totalSocialFund: 630000,
      isActive: true,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupModel(
      id: "GROUP-005",
      number: "05",
      regulation: "Peraturan Kelompok No. 05/2025",
      jointLiabilityFundAmount: 58000,
      groupFundAmount: 34000,
      socialFundAmount: 24000,
      totalJointLiabilityFund: 1580000,
      totalGroupFund: 940000,
      totalSocialFund: 640000,
      isActive: false,
      workArea: dummyWorkAreas[0],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: "GROUP-006",
      number: "06",
      regulation: "Peraturan Kelompok No. 06/2025",
      jointLiabilityFundAmount: 60000,
      groupFundAmount: 35000,
      socialFundAmount: 25000,
      totalJointLiabilityFund: 1600000,
      totalGroupFund: 950000,
      totalSocialFund: 650000,
      isActive: true,
      workArea: dummyWorkAreas[1],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: "GROUP-007",
      number: "07",
      regulation: "Peraturan Kelompok No. 07/2025",
      jointLiabilityFundAmount: 62000,
      groupFundAmount: 36000,
      socialFundAmount: 26000,
      totalJointLiabilityFund: 1620000,
      totalGroupFund: 960000,
      totalSocialFund: 660000,
      isActive: false,
      workArea: dummyWorkAreas[1],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: "GROUP-008",
      number: "08",
      regulation: "Peraturan Kelompok No. 08/2025",
      jointLiabilityFundAmount: 64000,
      groupFundAmount: 37000,
      socialFundAmount: 27000,
      totalJointLiabilityFund: 1640000,
      totalGroupFund: 970000,
      totalSocialFund: 670000,
      isActive: true,
      workArea: dummyWorkAreas[2],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: "GROUP-009",
      number: "09",
      regulation: "Peraturan Kelompok No. 09/2025",
      jointLiabilityFundAmount: 66000,
      groupFundAmount: 38000,
      socialFundAmount: 28000,
      totalJointLiabilityFund: 1660000,
      totalGroupFund: 980000,
      totalSocialFund: 680000,
      isActive: true,
      workArea: dummyWorkAreas[3],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),

    GroupModel(
      id: "GROUP-010",
      number: "10",
      regulation: "Peraturan Kelompok No. 10/2025",
      jointLiabilityFundAmount: 68000,
      groupFundAmount: 39000,
      socialFundAmount: 29000,
      totalJointLiabilityFund: 1680000,
      totalGroupFund: 990000,
      totalSocialFund: 690000,
      isActive: false,
      workArea: dummyWorkAreas[3],
      chairman: dummyUsers[1],
      facilitator: dummyUsers[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final dummyGroupMembers = <GroupMemberModel>[
    GroupMemberModel(
      id: 'GROUP-MEMBER-001',
      isActive: true,
      note: 'Anggota aktif dengan kontribusi rutin.',
      user: dummyUsers[4],
      group: dummyGroups[0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupMemberModel(
      id: 'GROUP-MEMBER-002',
      isActive: false,
      note: 'Status nonaktif karena tidak hadir 3 bulan.',
      user: dummyUsers[5],
      group: dummyGroups[1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    GroupMemberModel(
      id: 'GROUP-MEMBER-003',
      isActive: true,
      note: 'Ketua kelompok.',
      user: dummyUsers[6],
      group: dummyGroups[2],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];
}
