import 'package:get/get.dart';

final class LanguageHelper extends Translations {
  static void addData(Map<String, Map<String, String>> values) {
    for (MapEntry<String, Map<String, String>> value in values.entries) {
      for (MapEntry<String, String> val in value.value.entries) {
        if (_data[value.key] != null) {
          _data[value.key]!.addAll({val.key: val.value});
        } else {
          _data[value.key] = {val.key: val.value};
        }
      }
    }
  }

  static final Map<String, Map<String, String>> _data = {
    'en_US': {
      'January': 'January',
      'February': 'February',
      'March': 'March',
      'April': 'April',
      'May': 'May',
      'June': 'June',
      'July': 'July',
      'August': 'August',
      'September': 'September',
      'October': 'October',
      'November': 'November',
      'December': 'December',
      'Sunday': 'Sunday',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Saturday': 'Saturday',
      'Ok': 'Ok',
      'Cancel': 'Cancel',
      'Gallery': 'Gallery',
      'Camera': 'Camera',
      'Delete': 'Delete',
      'File': 'File',
      'Save': 'Save',
      'Retry': 'Retry',
      'An error occured!': 'An error occured!',
      'Error': 'Error',
      'Warning': 'Warning',
      'Save changes?': 'Save changes?',
      'Don\'t save': 'Don\'t save',
      'Change logo': 'Change logo',
      'Change theme': 'Change theme',
      'Theme': 'Theme',
      'System': 'System',
      'Dark': 'Dark',
      'Light': 'Light',
      'Don\'t use dynamic colors': 'Don\'t use dynamic colors',
      'Use dynamic colors': 'Use dynamic colors',
      'With custom colors': 'With custom colors',
      'Language': 'Language',
      'Choose language': 'Choose language',
      'No data': 'No data',
      'Data not found': 'Data not found',
      'Search language': 'Search language',
      'Information': 'Information',
      'Yes': 'Yes',
      'No': 'No',
      'Minimum %s characters': 'Minimum %s characters',
      'Contains lowercase letters': 'Contains lowercase letters',
      'Contains uppercase letters': 'Contains uppercase letters',
      'Contains numbers': 'Contains numbers',
      'Contains special characters': 'Contains special characters',
      'Password does not meet criteria': 'Password does not meet criteria',
      'Continue': 'Continue',
      '%s%': '%s%',
      '%s Seconds': '%s Seconds',
      'You are offline': 'You are offline',
      'Not in order (123, abc, ABC)': 'Not in order (123, abc, ABC)',
    },
    'id_ID': {
      'January': 'Januari',
      'February': 'Februari',
      'March': 'Maret',
      'April': 'April',
      'May': 'Mei',
      'June': 'Juni',
      'July': 'Juli',
      'August': 'Agustus',
      'September': 'September',
      'October': 'Oktober',
      'November': 'November',
      'December': 'Desember',
      'Sunday': 'Minggu',
      'Monday': 'Senin',
      'Tuesday': 'Selasa',
      'Wednesday': 'Rabu',
      'Thursday': 'Kamis',
      'Friday': 'Jum\'at',
      'Saturday': 'Sabtu',
      'Ok': 'Ok',
      'Cancel': 'Batal',
      'Gallery': 'Galeri',
      'Camera': 'Kamera',
      'Delete': 'Hapus',
      'File': 'File',
      'Save': 'Simpan',
      'Retry': 'Coba lagi',
      'An error occured!': 'Terjadi error!',
      'Error': 'Error',
      'Warning': 'Peringatan',
      'Save changes?': 'Simpan perubahan?',
      'Don\'t save': 'Jangan simpan',
      'Change logo': 'Ganti logo',
      'Change theme': 'Ganti tema',
      'Theme': 'Tema',
      'System': 'Sistem',
      'Dark': 'Gelap',
      'Light': 'Terang',
      'Don\'t use dynamic colors': 'Jangan gunakan warna dinamis',
      'Use dynamic colors': 'Gunakan warna dinamis',
      'With custom colors': 'Dengan warna khusus',
      'Language': 'Bahasa',
      'Choose language': 'Pilih bahasa',
      'No data': 'Tidak ada data',
      'Data not found': 'Data tidak ditemukan',
      'Search language': 'Cari bahasa',
      'Information': 'Informasi',
      'Yes': 'Ya',
      'No': 'Tidak',
      'Minimum %s characters': 'Minimal %s karakter',
      'Contains lowercase letters': 'Berisi huruf kecil',
      'Contains uppercase letters': 'Berisi huruf besar',
      'Contains numbers': 'Berisi angka',
      'Contains special characters': 'Berisi karakter spesial',
      'Password does not meet criteria': 'Kata sandi tidak memenuhi kriteria',
      'Continue': 'Lanjutkan',
      '%s%': '%s%',
      '%s Seconds': '%s Detik',
      'You are offline': 'Anda sedang offline',
      'Not in order (123, abc, ABC)': 'Tidak berurutan (123, abc, ABC)',
    },
  };

  @override
  Map<String, Map<String, String>> get keys => _data;
}
